language: python
python:
  - "2.7"
cache: pip
install:
  - pip install Flask
  - pip install flask_cors
  - pip install wtforms
  - pip install coveralls
script:
  - coverage run --source=myapp unit_tests.py
  #- python unit_tests.py
after_success: coveralls
